import type { Category, Severity } from "./types.js";
import { TARGET_EFFECT_RC } from "./version.js";

export type RuleDefinition = {
  id: string;
  severity: Severity;
  category: Category;
  message: string;
  hint: string;
  bad: string;
  good: string;
};

function r(
  id: string,
  severity: Severity,
  category: Category,
  message: string,
  hint: string,
  bad: string,
  good: string,
): RuleDefinition {
  return { id: `effect-doctor/${id}`, severity, category, message, hint, bad, good };
}

export const RULES: readonly RuleDefinition[] = [
  r("floating-effect", "error", "correctness", "Effect criado e descartado — nunca roda.", "Atribua, `yield*` ou rode no boundary.", "Effect.log(\"hi\")", "yield* Effect.log(\"hi\")"),
  r("run-inside-effect", "error", "anti-pattern", "Effect.run* dentro de gen/fn solta outro runtime.", "Dentro do gen: `yield*`. run* só no entry point.", "const x = yield* Effect.gen(function* () { Effect.runPromise(op) })", "const x = yield* op"),
  r("missing-yield-star", "error", "correctness", "`yield` sem `*` não propaga E/R.", "Sempre `yield*`.", "const user = yield getUser(id)", "const user = yield* getUser(id)"),
  r("try-catch-in-gen", "error", "anti-pattern", "try/catch no gen não vê falha do Effect.", "Effect.try / tryPromise / catchTag / catch.", "try { yield* op } catch (e) {}", "yield* Effect.tryPromise({ try: () => op, catch: (e) => new DbError({ cause: e }) })"),
  r("try-finally-in-gen", "warning", "anti-pattern", "try/finally no gen não é interruption-safe.", "Effect.acquireRelease + Effect.scoped.", "try { yield* use(res) } finally { yield* close(res) }", "yield* Effect.acquireRelease(open, close)"),
  r("throw-in-effect", "error", "correctness", "`throw` vira defect, não erro tipado.", "Effect.fail(new TaggedError(...)) ou `return yield* new TaggedError(...)`.", "throw new Error(\"nope\")", "return yield* new NotFound({ id })"),
  r("schema-sync-in-effect", "error", "anti-pattern", "Schema.*Sync lança e foge do canal E.", `No RC ${TARGET_EFFECT_RC}: Schema.decodeUnknownEffect.`, "Schema.decodeUnknownSync(User)(raw)", "yield* Schema.decodeUnknownEffect(User)(raw)"),
  r("schema-decode-v3", "error", "v4-migration", "Schema.decodeUnknown (v3). No RC o Effect se chama decodeUnknownEffect.", "Hoiste o codec e dê yield*.", "yield* Schema.decodeUnknown(User)(raw)", "const decodeUser = Schema.decodeUnknownEffect(User)\nyield* decodeUser(raw)"),
  r("return-effect-in-gen", "warning", "anti-pattern", "`return Effect.*` aninha Effect<Effect<...>>.", "`return yield* efeito`.", "return Effect.succeed(1)", "return yield* Effect.succeed(1)"),
  r("map-returning-effect", "warning", "correctness", "Effect.map com callback que devolve Effect — o interno não roda.", "Effect.flatMap.", "Effect.map(x => Effect.succeed(x))", "Effect.flatMap(x => Effect.succeed(x))"),
  r("promise-all", "warning", "anti-pattern", "Promise.all perde interrupção e E tipado.", "Effect.all(..., { concurrency }).", "Promise.all([a, b])", "yield* Effect.all([a, b], { concurrency: 2 })"),
  r("new-promise", "warning", "idiomatic", "`new Promise` em código Effect.", "Effect.promise / tryPromise / async.", "new Promise((ok) => ok(1))", "Effect.promise(() => fetch(url).then(r => r.json()))"),
  r("lazy-promise-in-sync", "warning", "anti-pattern", "Effect.sync async — sync tem que ser síncrono.", "Effect.tryPromise.", "Effect.sync(async () => 1)", "Effect.tryPromise({ try: () => fetch(url), catch: (e) => new HttpError({ cause: e }) })"),
  r("then-in-sync", "warning", "anti-pattern", ".then dentro de Effect.sync.", "Effect.tryPromise.", "Effect.sync(() => fetch(url).then(r => r.json()))", "Effect.tryPromise({ try: () => fetch(url).then(r => r.json()), catch: (e) => new HttpError({ cause: e }) })"),
  r("multiple-provide", "warning", "architecture", "Vários Effect.provide — ciclo de vida duplicado.", "Um Layer composto, um provide no entry.", "op.pipe(Effect.provide(A), Effect.provide(B))", "op.pipe(Effect.provide(Layer.provide(B, A)))"),
  r("process-env", "warning", "idiomatic", "process.env cru.", "Config.string / Config.redacted.", "process.env.TOKEN", "yield* Config.redacted(\"TOKEN\")"),
  r("json-parse", "warning", "idiomatic", "JSON.parse lança e devolve any.", "Schema.decodeUnknownEffect(Schema.fromJsonString(...)).", "JSON.parse(text)", "yield* Schema.decodeUnknownEffect(UserFromJson)(text)"),
  r("global-console", "warning", "idiomatic", "console.* fora do logger Effect.", "Effect.log / logInfo / logError / logWarning.", "console.log(user)", "yield* Effect.logInfo(user)"),
  r("global-fetch", "warning", "idiomatic", "fetch global sem retry/timeout/E.", "HttpClient do effect (unstable/http no RC) ou tryPromise como ponte.", "yield* Effect.tryPromise(() => fetch(url))", "yield* http.get(url)"),
  r("global-date", "warning", "idiomatic", "Date.now / new Date() não injetável.", "Clock.currentTimeMillis / DateTime.now.", "Date.now()", "yield* Clock.currentTimeMillis"),
  r("global-random", "warning", "idiomatic", "Math.random() não injetável.", "Random.next.", "Math.random()", "yield* Random.next"),
  r("crypto-random-uuid", "warning", "idiomatic", "crypto.randomUUID fora do Random.", "Random.nextUUIDv4 ou equivalente do RC.", "crypto.randomUUID()", "yield* Random.nextUUIDv4"),
  r("global-timers", "warning", "idiomatic", "setTimeout/setInterval fogem da interrupção.", "Effect.sleep / Schedule.", "setTimeout(fn, 1000)", "yield* Effect.sleep(\"1 second\")"),
  r("string-fail", "warning", "anti-pattern", "Effect.fail(\"string\") apaga o canal E.", "Schema.TaggedErrorClass / Data.TaggedError.", "Effect.fail(\"nope\")", "class NotFound extends Schema.TaggedErrorClass<NotFound>()(\"NotFound\", { id: Schema.String }) {}"),
  r("unsafe-assertion", "warning", "type-safety", "`as unknown as` apaga E/R.", "Schema.decode / catchTag / provide.", "value as unknown as User", "yield* Schema.decodeUnknownEffect(User)(value)"),
  r("or-die", "info", "correctness", "orDie silencia erro recuperável.", "catchTag no tagged error; orDie só para invariante.", "op.pipe(Effect.orDie)", "op.pipe(Effect.catchTag(\"NotFound\", () => Effect.succeed(fallback)))"),
  r("succeed-undefined", "info", "idiomatic", "Effect.succeed(undefined) → Effect.void.", "Effect.void.", "Effect.succeed(undefined)", "Effect.void"),
  r("map-as-void", "info", "idiomatic", "map(() => undefined) → asVoid.", "Effect.asVoid.", "Effect.map(() => undefined)", "Effect.asVoid"),
  r("unnecessary-gen", "info", "idiomatic", "gen com um único `return yield*` é ruído.", "Use o Effect direto.", "Effect.gen(function* () { return yield* op })", "op"),
  r("nested-gen-yield", "info", "idiomatic", "`yield* Effect.gen(...)` aninhado.", "Inline o corpo no gen de fora.", "yield* Effect.gen(function* () { yield* inner })", "yield* inner"),
  r("effect-fn-iife", "warning", "idiomatic", "Effect.fn(...)() IIFE.", "Effect.gen, ou dê nome ao fn.", "Effect.fn(\"x\")(function* () { return 1 })()", "Effect.gen(function* () { return 1 })"),
  r("unnecessary-pipe", "info", "idiomatic", "pipe() vazio ou inútil.", "Remova o pipe.", "value.pipe()", "value"),
  r("unnecessary-pipe-chain", "info", "idiomatic", "pipe encadeado — junte num só.", "Um .pipe(a, b, c).", "op.pipe(a).pipe(b)", "op.pipe(a, b)"),
  r("effect-do", "info", "idiomatic", "Effect.Do/bind — no RC prefira gen/fn.", "Effect.gen ou Effect.fn.", "Effect.Do.pipe(Effect.bind(\"x\", () => op))", "Effect.gen(function* () { const x = yield* op })"),
  r("fn-untraced", "info", "idiomatic", "fnUntraced sem motivo de hot-path.", "Effect.fn(\"NomeDaOp\") — span grátis.", "Effect.fnUntraced(function* () {})", "Effect.fn(\"LoadUser\")(function* (id: string) { ... })"),
  r("prefer-effect-fn", "warning", "idiomatic", "Função que só devolve Effect.gen — Effect.fn ganha span.", "Effect.fn(\"Op\").", "const load = (id: string) => Effect.gen(function* () { ... })", "const load = Effect.fn(\"LoadUser\")(function* (id: string) { ... })"),
  r("prefer-catch-tag", "warning", "idiomatic", "catch ramificando em e._tag.", "Effect.catchTag / catchTags.", "Effect.catch((e) => e._tag === \"NotFound\" ? fallback : Effect.fail(e))", "Effect.catchTag(\"NotFound\", () => fallback)"),
  r("prefer-tagged-error", "warning", "idiomatic", "class extends Error — sem _tag.", "Schema.TaggedErrorClass no RC.", "class E extends Error {}", "class E extends Schema.TaggedErrorClass<E>()(\"E\", { id: Schema.String }) {}"),
  r("tag-string-comparison", "warning", "idiomatic", "x._tag === \"Ready\" na mão.", "Match / Predicate.isTagged / catchTag.", "if (result._tag === \"Ready\") use(result)", "Match.value(result).pipe(Match.tag(\"Ready\", use), Match.orElse(() => {}))"),
  r("manual-tagged-construction", "warning", "idiomatic", "Objeto literal `{ _tag: \"X\" }`.", "Construtor TaggedErrorClass / Data.taggedEnum.", "const r = { _tag: \"Ready\", value }", "Ready.make({ value })"),
  r("prefer-match", "warning", "idiomatic", "Ternário encadeado — Match no RC.", "Match.value + Match.when + Match.orElse.", "k === \"a\" ? \"A\" : k === \"b\" ? \"B\" : \"C\"", "Match.value(k).pipe(Match.when(\"a\", () => \"A\"), Match.when(\"b\", () => \"B\"), Match.orElse(() => \"C\"))"),
  r("config-redacted", "warning", "security", "Segredo via Config.string vaza em log.", "Config.redacted(\"TOKEN\").", "yield* Config.string(\"TOKEN\")", "yield* Config.redacted(\"TOKEN\")"),
  r("all-missing-concurrency", "info", "idiomatic", "Effect.all sem { concurrency } é sequencial.", "Deixe explícito: 1, N ou \"unbounded\".", "Effect.all([a, b])", "Effect.all([a, b], { concurrency: 2 })"),
  r("hoist-schema-codec", "info", "idiomatic", "decodeUnknownEffect dentro da função recompila o codec.", "const decodeX = Schema.decodeUnknownEffect(X) no módulo.", "function run() { return Schema.decodeUnknownEffect(User)(raw) }", "const decodeUser = Schema.decodeUnknownEffect(User)\nfunction run() { return decodeUser(raw) }"),
  r("sleep-raw-millis", "info", "idiomatic", "Effect.sleep(número) — use Duration.", "Effect.sleep(\"100 millis\") ou Duration.millis(100).", "Effect.sleep(100)", "Effect.sleep(\"100 millis\")"),
  r("node-fs-import", "warning", "idiomatic", "node:fs em código Effect.", "FileSystem do effect (platform).", "import * as fs from \"node:fs\"", "const fs = yield* FileSystem.FileSystem"),
  r("catch-to-null", "warning", "correctness", "catch que devolve null engole o erro.", "catchTag + Option, ou falhe de forma tipada.", "Effect.catch(() => null)", "Effect.catchTag(\"NotFound\", () => Effect.succeed(Option.none()))"),
  r("v4-catch-all", "error", "v4-migration", "Effect.catchAll — no RC é Effect.catch.", "Troque catchAll → catch.", "Effect.catchAll((e) => recover(e))", "Effect.catch((e) => recover(e))"),
  r("v4-catch-all-cause", "error", "v4-migration", "catchAllCause → catchCause.", "Effect.catchCause.", "Effect.catchAllCause((c) => recover)", "Effect.catchCause((c) => recover)"),
  r("v4-catch-some", "error", "v4-migration", "catchSome → catchFilter + Filter.", "Effect.catchFilter(Filter.fromPredicate(...), handler).", "Effect.catchSome((e) => Option.some(recover))", "Effect.catchFilter(Filter.fromPredicate(pred), handler)"),
  r("v4-fork", "error", "v4-migration", "Effect.fork → Effect.forkChild no RC.", "forkChild (filho) ou forkDetach (daemon).", "Effect.fork(op)", "Effect.forkChild(op)"),
  r("v4-fork-daemon", "error", "v4-migration", "forkDaemon → forkDetach.", "Effect.forkDetach(op).", "Effect.forkDaemon(op)", "Effect.forkDetach(op)"),
  r("v4-fork-all", "error", "v4-migration", "forkAll foi removido no RC.", "forkChild em cada um, ou Effect.all com concurrency.", "Effect.forkAll(ops)", "Effect.forEach(ops, Effect.forkChild, { concurrency: \"unbounded\" })"),
  r("v4-context-tag", "error", "v4-migration", "Context.Tag / GenericTag / Effect.Tag — no RC é Context.Service.", "class X extends Context.Service<X, Shape>()(\"X\") {}", "class Db extends Context.Tag(\"Db\")<Db, Shape>() {}", "class Db extends Context.Service<Db, Shape>()(\"Db\") {}"),
  r("v4-effect-service", "error", "v4-migration", "Effect.Service — no RC é Context.Service + Layer.effect (sem .Default).", "Context.Service + static layer = Layer.effect(this, this.make).", "class Log extends Effect.Service<Log>()(\"Log\", { effect: ... }) {}", "class Log extends Context.Service<Log>()(\"Log\", { make: ... }) { static layer = Layer.effect(this, this.make) }"),
  r("v4-layer-scoped", "warning", "v4-migration", "Layer.scoped no RC virou Layer.effect (scoped é o Effect).", "Layer.effect(tag, Effect.acquireRelease(...)).", "Layer.scoped(Tag, acquire)", "Layer.effect(Tag, Effect.acquireRelease(acquire, release))"),
  r("v4-option-from-nullable", "error", "v4-migration", "Option.fromNullable → fromNullishOr.", "Option.fromNullishOr(value).", "Option.fromNullable(x)", "Option.fromNullishOr(x)"),
  r("v4-fiber-ref", "error", "v4-migration", "FiberRef foi para Context.Reference.", "Context.Reference(\"Name\", { defaultValue: () => ... }).", "FiberRef.make(0)", "Context.Reference<number>(\"Counter\", { defaultValue: () => 0 })"),
  r("v4-effect-runtime", "error", "v4-migration", "Effect.runtime / Runtime<R> removidos.", "Effect.context + runForkWith / ManagedRuntime.", "const rt = yield* Effect.runtime()", "const ctx = yield* Effect.context<App>()"),
  r("v4-platform-import", "error", "v4-migration", "@effect/platform|rpc|cluster no RC entram em effect / effect/unstable/*.", "Importe de effect ou effect/unstable/http etc., versão alinhada ao RC.", "import { HttpClient } from \"@effect/platform\"", "import { HttpClient } from \"effect/unstable/http\""),
  r("v4-schema-tagged-error", "warning", "v4-migration", "Schema.TaggedError → TaggedErrorClass no RC.", "Schema.TaggedErrorClass<E>()(\"E\", fields).", "class E extends Schema.TaggedError<E>(\"E\")({}) {}", "class E extends Schema.TaggedErrorClass<E>()(\"E\", { id: Schema.String }) {}"),
  r("not-on-effect-rc", "error", "v4-migration", `package.json não está no Effect RC alvo (${TARGET_EFFECT_RC}).`, `npm install effect@rc  →  ${TARGET_EFFECT_RC}`, "\"effect\": \"3.16.0\"", `\"effect\": \"${TARGET_EFFECT_RC}\"`),
  r("missing-effect-dependency", "error", "architecture", "Importa effect sem declarar no package.json.", "Adicione effect@rc nas dependencies.", "import { Effect } from \"effect\"", `\"dependencies\": { \"effect\": \"${TARGET_EFFECT_RC}\" }`),
  r("duplicate-effect-package", "error", "architecture", "@effect/io ou @effect/data junto com effect — duas runtimes.", "Só `effect` no RC.", "\"@effect/io\": \"0.40.0\"", "remova @effect/io / @effect/data"),
  r("legacy-default-layer", "warning", "v4-migration", ".Default / .Live no RC virou .layer / .layerTest.", "static readonly layer = Layer.effect(...).", "Effect.provide(Logger.Default)", "Effect.provide(Logger.layer)"),
  r("if-else-chain", "warning", "agent-hygiene", "if/else if/else — agente inventando control flow.", "Match.exhaustive ou mapa de handlers.", "if (k===\"a\") {} else if (k===\"b\") {} else {}", "Match.value(k).pipe(Match.when(\"a\", ...), Match.when(\"b\", ...), Match.orElse(...))"),
  r("raw-loop", "warning", "agent-hygiene", "for/while cru em arquivo Effect.", "Effect.forEach / Effect.all / Array.* .", "for (const x of xs) { yield* f(x) }", "yield* Effect.forEach(xs, f, { concurrency: 4 })"),
  r("let-mutation", "warning", "agent-hygiene", "`let`/`var` — mutate em vez de construir.", "const + reduce / Match / pipeline.", "let total = 0; total += n", "const total = ns.reduce((a, n) => a + n, 0)"),
  r("inline-dynamic-import", "warning", "agent-hygiene", "import() inline.", "import estático no topo (exceto code-split deliberado).", "const m = await import(\"./x\")", "import * as X from \"./x.ts\""),
  r("explicit-any", "warning", "type-safety", "`any` — o agente silenciou o checker.", "unknown + Schema, ou o tipo certo.", "function f(x: any) {}", "function f(x: unknown) { return Schema.decodeUnknownEffect(User)(x) }"),
  r("non-null-assertion", "warning", "type-safety", "`x!` — mentira para o tipo.", "Option / narrowing / Schema.", "user!.id", "Option.map(user, (u) => u.id)"),
  r("empty-catch", "warning", "type-safety", "catch {} engole falha.", "catchTag ou Effect.ignore só se for explícito.", "try { x() } catch {}", "yield* Effect.try({ try: x, catch: (e) => new XError({ cause: e }) })"),
  r("ts-ignore", "warning", "type-safety", "@ts-ignore / @ts-expect-error.", "Conserte o tipo. Se inevitável: comentário SAFETY: motivo.", "// @ts-ignore", "yield* Schema.decodeUnknownEffect(User)(raw)"),
  r("default-export", "info", "agent-hygiene", "export default — identidade instável (exceto alchemy.run.ts).", "export const / export class.", "export default function run() {}", "export const run = Effect.fn(\"Run\")(function* () {})"),
  r("max-params", "info", "maintainability", "Mais de 4 parâmetros.", "Um objeto de opções / Data.struct.", "function f(a,b,c,d,e) {}", "function f(opts: { a: A; b: B; c: C; d: D; e: E }) {}"),
  r("max-nesting", "warning", "maintainability", "if/for/while aninhados > 4.", "early return, helper, Match.", "if (a) { if (b) { if (c) { if (d) { if (e) {} } } } }", "guarde cada condição e use Match / early return"),
  r("giant-gen", "warning", "maintainability", "Effect.gen com 80+ linhas.", "Extraia passos que retornam Effect; compose com yield*.", "Effect.gen(function* () { /* 120 linhas */ })", "const load = Effect.fn(\"Load\")(function* () { ... })\nconst save = Effect.fn(\"Save\")(function* () { ... })"),
  r("file-too-long", "warning", "agent-hygiene", "Arquivo > 650 linhas.", "Módulos focados — um conceito por arquivo.", "user-service.ts com 900 linhas", "user-get.ts, user-save.ts, user-layer.ts"),
  r("hardcoded-secret", "error", "security", "Segredo/token no fonte.", "Config.redacted / env. Nunca literal.", "const token = \"sk_live_abc\"", "const token = yield* Config.redacted(\"STRIPE_TOKEN\")"),
  r("alchemy-missing-entry", "warning", "alchemy", "Dependência alchemy sem alchemy.run.ts.", "Crie alchemy.run.ts com export default Alchemy.Stack.", "package.json tem alchemy, sem arquivo de stack", "export default Alchemy.Stack(\"App\", { providers, state }, program)"),
  r("alchemy-missing-stack", "error", "alchemy", "Sem `export default Alchemy.Stack(...)`.", "A CLI do Alchemy procura Stack default-exported.", "export const stack = Alchemy.Stack(...)", "export default Alchemy.Stack(\"App\", { providers, state }, program)"),
  r("alchemy-missing-providers", "error", "alchemy", "Stack sem providers.", "{ providers: Cloudflare.providers(), state }.", "Alchemy.Stack(\"App\", { state }, program)", "Alchemy.Stack(\"App\", { providers: Cloudflare.providers(), state: Cloudflare.state() }, program)"),
  r("alchemy-secret-in-source", "error", "alchemy", "Credencial no stack. Doctor não faz deploy/login.", "Perfil ~/.alchemy ou Config — nunca literal.", "const token = \"cf_abc\"", "yield* Config.redacted(\"CLOUDFLARE_API_TOKEN\")"),

  r("v4-catch-all-defect", "error", "v4-migration", "catchAllDefect → catchDefect no RC.", "Effect.catchDefect.", "Effect.catchAllDefect((d) => recover)", "Effect.catchDefect((d) => recover)"),
  r("v4-catch-some-cause", "error", "v4-migration", "catchSomeCause → catchCauseFilter.", "Effect.catchCauseFilter(Filter.fromPredicate(...), handler).", "Effect.catchSomeCause((c) => Option.some(recover))", "Effect.catchCauseFilter(Filter.fromPredicate(pred), handler)"),
  r("v4-catch-some-defect", "error", "v4-migration", "catchSomeDefect foi removido no RC.", "Effect.catchDefect + Filter, ou catchCauseFilter.", "Effect.catchSomeDefect((d) => Option.some(recover))", "Effect.catchDefect((d) => recover)"),
  r("v4-fork-error-handler", "error", "v4-migration", "forkWithErrorHandler foi removido no RC.", "forkChild + tapError / catch no filho.", "Effect.forkWithErrorHandler(op, onError)", "yield* Effect.forkChild(op.pipe(Effect.tapError(onError)))"),
  r("v4-effect-unit", "error", "v4-migration", "Effect.unit não existe no RC — é Effect.void.", "Effect.void.", "Effect.unit", "Effect.void"),
  r("v4-gen-adapter", "error", "v4-migration", "Adapter `_` / `adapter` no Effect.gen foi removido.", "yield* op direto.", "Effect.gen(function* (_) { const x = yield* _(op) })", "Effect.gen(function* () { const x = yield* op })"),
  r("v4-gen-self", "error", "v4-migration", "Effect.gen(this, function* ) mudou no RC.", "Effect.gen({ self: this }, function* () { ... }).", "Effect.gen(this, function* () { return this.value })", "Effect.gen({ self: this }, function* () { return this.value })"),
  r("v4-cause-fail-type", "error", "v4-migration", "Cause v4 é lista de reasons: isFailType/isDie/isFailure sumiram.", "Cause.isFailReason / hasDies / hasFails / hasInterrupts.", "Cause.isFailType(cause)", "Cause.isFailReason(reason)"),
  r("v4-scope-extend", "error", "v4-migration", "Scope.extend → Scope.provide.", "Scope.provide(effect, scope).", "Scope.extend(effect, scope)", "Scope.provide(effect, scope)"),
  r("v4-schema-union-args", "error", "v4-migration", "Schema.Union(A, B) no RC é Schema.Union([A, B]).", "Passe um array.", "Schema.Union(A, B)", "Schema.Union([A, B])"),
  r("v4-schema-literals", "error", "v4-migration", "Schema.Literal(\"a\", \"b\") no RC é Schema.Literals([\"a\", \"b\"]).", "Schema.Literal só aceita um valor; vários → Literals.", "Schema.Literal(\"a\", \"b\")", "Schema.Literals([\"a\", \"b\"])"),
  r("v4-config-secret", "error", "v4-migration", "Config.secret → Config.redacted.", "Config.redacted(\"TOKEN\").", "yield* Config.secret(\"TOKEN\")", "yield* Config.redacted(\"TOKEN\")"),
  r("v4-legacy-effect-import", "error", "v4-migration", "@effect/schema|data|match|io não existem no RC — está tudo em `effect`.", "import { Schema, Match, Data } from \"effect\".", "import * as Schema from \"@effect/schema\"", "import { Schema } from \"effect\""),
  r("v4-unstable-import", "info", "v4-migration", "effect/unstable/* pode quebrar em minor do RC.", "Pode usar; pinne a versão exata do RC.", "import { HttpClient } from \"effect/unstable/http\"", "pinne effect@4.0.0-rc.115 e acompanhe o changelog"),
  r("v4-schema-tagged-struct", "info", "v4-migration", "Schema.Struct com campo `_tag` — use TaggedStruct.", "Schema.TaggedStruct(\"Ready\", { value: Schema.String }).", "Schema.Struct({ _tag: Schema.Literal(\"Ready\"), value: Schema.String })", "Schema.TaggedStruct(\"Ready\", { value: Schema.String })"),
  r("v4-fiber-refs-differ", "error", "v4-migration", "FiberRefs / Differ removidos no RC.", "Context.Reference ou Effect.provideService.", "FiberRefs.empty", "Context.Reference(\"Flag\", { defaultValue: () => false })"),

  r("schema-class-self-mismatch", "error", "correctness", "Self type do Schema/Context.Service não é a classe.", "class Foo extends Schema.Class<Foo>(\"Foo\")({ ... }).", "class Foo extends Schema.Class<Bar>(\"Foo\")({ id: Schema.String }) {}", "class Foo extends Schema.Class<Foo>(\"Foo\")({ id: Schema.String }) {}"),
  r("schema-constructor-override", "error", "correctness", "constructor em Schema.Class quebra o decode.", "Factory estática / Schema.transform. Sem constructor.", "class User extends Schema.Class<User>(\"User\")({ id: Schema.String }) { constructor() { super({ id: \"0\" }) } }", "class User extends Schema.Class<User>(\"User\")({ id: Schema.String }) { static empty = () => User.make({ id: \"0\" }) }"),
  r("schema-redundant-tag-id", "info", "idiomatic", "TaggedError/Class com identifier === tag é ruído.", "Schema.TaggedErrorClass<E>()(\"E\", fields).", "class E extends Schema.TaggedError<E>(\"E\")(\"E\", {}) {}", "class E extends Schema.TaggedErrorClass<E>()(\"E\", { id: Schema.String }) {}"),
  r("schema-any", "warning", "type-safety", "Schema.Any / Schema.Unknown sem refine no boundary.", "Schema.Unknown + decodeUnknownEffect no edge; no domínio use Struct.", "Schema.Any", "Schema.Struct({ id: Schema.String })"),
  r("instance-of-schema", "warning", "idiomatic", "`instanceof` em classe Schema — use Schema.is.", "Schema.is(User)(value).", "if (value instanceof User) {}", "if (Schema.is(User)(value)) {}"),
  r("async-callback-in-combinator", "error", "correctness", "Callback async em map/flatMap/tap — o Promise não é awaited.", "Effect.tryPromise / flatMap com Effect.", "Effect.map(user, async (u) => enrich(u))", "Effect.flatMap(user, (u) => Effect.tryPromise({ try: () => enrich(u), catch: (e) => new EnrichError({ cause: e }) }))"),
  r("try-untyped-catch", "info", "idiomatic", "Effect.try/tryPromise sem `{ try, catch }` vira UnknownException.", "Objeto { try, catch } com TaggedError.", "Effect.tryPromise(() => fetch(url))", "Effect.tryPromise({ try: (signal) => fetch(url, { signal }), catch: (e) => new FetchError({ cause: e }) })"),
  r("try-promise-abort-signal", "info", "idiomatic", "tryPromise com fetch sem AbortSignal — interrupção não cancela.", "try: (signal) => fetch(url, { signal }).", "Effect.tryPromise({ try: () => fetch(url), catch: (e) => new FetchError({ cause: e }) })", "Effect.tryPromise({ try: (signal) => fetch(url, { signal }), catch: (e) => new FetchError({ cause: e }) })"),
  r("runsync-on-async", "error", "correctness", "runSync em Effect.promise/sleep/async explode AsyncFiberException.", "Effect.runPromise.", "Effect.runSync(Effect.promise(() => fetch(url)))", "await Effect.runPromise(Effect.tryPromise({ try: () => fetch(url), catch: (e) => new FetchError({ cause: e }) }))"),
  r("map-flatten", "info", "idiomatic", "map + flatten = flatMap.", "Effect.flatMap.", "op.pipe(Effect.map(toEffect), Effect.flatten)", "op.pipe(Effect.flatMap(toEffect))"),
  r("catch-to-map-error", "info", "idiomatic", "catch que só faz Effect.fail(wrap(e)) é mapError.", "Effect.mapError.", "Effect.catch((e) => Effect.fail(new Wrapped({ cause: e })))", "Effect.mapError((e) => new Wrapped({ cause: e }))"),
  r("flatmap-to-map", "info", "idiomatic", "flatMap que só faz Effect.succeed(f(x)) é map.", "Effect.map.", "Effect.flatMap((x) => Effect.succeed(x * 2))", "Effect.map((x) => x * 2)"),
  r("succeed-over-sync-literal", "info", "idiomatic", "Effect.sync(() => literal) — use succeed.", "Effect.succeed(42).", "Effect.sync(() => 42)", "Effect.succeed(42)"),
  r("fail-yieldable", "info", "idiomatic", "Effect.fail(new TaggedError) — o erro já é yieldable.", "return yield* new NotFound({ id }).", "return yield* Effect.fail(new NotFound({ id }))", "return yield* new NotFound({ id })"),
  r("nested-flatmap", "info", "idiomatic", "flatMap dentro de flatMap — gen fica plano.", "Effect.gen com yield*.", "Effect.flatMap(getUser, (u) => Effect.flatMap(getAccount(u), (a) => invoice(u, a)))", "Effect.gen(function* () { const u = yield* getUser; const a = yield* getAccount(u); return yield* invoice(u, a) })"),
  r("long-combinator-chain", "info", "idiomatic", "4+ flatMap/andThen no mesmo pipe.", "Effect.gen / Effect.fn.", "op.pipe(Effect.flatMap(a), Effect.flatMap(b), Effect.flatMap(c), Effect.flatMap(d))", "Effect.gen(function* () { const x = yield* op; const y = yield* a(x); return yield* d(y) })"),
  r("layer-mergeall-megalist", "info", "architecture", "Layer.mergeAll com 8+ camadas soltas.", "Compose módulos (infra, domínio) e merge os módulos.", "Layer.mergeAll(A,B,C,D,E,F,G,H,I)", "Layer.mergeAll(Infra, Domain, Http)"),
  r("timeout-over-race-sleep", "warning", "idiomatic", "Effect.race com sleep é timeout na mão.", "Effect.timeout(\"2 seconds\").", "Effect.race(fetchData, Effect.sleep(\"2 seconds\"))", "fetchData.pipe(Effect.timeout(\"2 seconds\"))"),
  r("fork-then-join", "warning", "idiomatic", "fork + join imediatamente = só yield* o efeito.", "yield* task. Fork só se o trabalho segue em paralelo.", "const f = yield* Effect.forkChild(task)\nconst x = yield* Fiber.join(f)", "const x = yield* task"),
  r("foreach-missing-concurrency", "info", "performance", "Effect.forEach sem { concurrency } é sequencial.", "Deixe explícito: 1, N ou \"unbounded\".", "Effect.forEach(ids, load)", "Effect.forEach(ids, load, { concurrency: 8 })"),
  r("unbounded-concurrency", "info", "performance", "concurrency: \"unbounded\" em coleção grande = N fibers.", "Número limitado ao recurso (pool, HTTP).", "Effect.forEach(ids, load, { concurrency: \"unbounded\" })", "Effect.forEach(ids, load, { concurrency: 10 })"),
  r("retry-without-predicate", "info", "architecture", "Effect.retry(Schedule) reexecuta 404 e bug.", "retry({ schedule, while }) só no erro transitório.", "Effect.retry(Schedule.exponential(\"100 millis\"))", "Effect.retry({ schedule: Schedule.exponential(\"100 millis\").pipe(Schedule.jittered), while: (e) => e._tag === \"Transient\" })"),
  r("schedule-exponential-jitter", "info", "performance", "Backoff sem jitter = thundering herd.", "Schedule.jittered.", "Schedule.exponential(\"100 millis\")", "Schedule.exponential(\"100 millis\").pipe(Schedule.jittered)"),
  r("schedule-exponential-cap", "info", "performance", "Exponential sem teto cresce sem fim.", "Schedule.either(Schedule.spaced(\"10 seconds\")).", "Schedule.exponential(\"100 millis\")", "Schedule.exponential(\"100 millis\").pipe(Schedule.jittered, Schedule.either(Schedule.spaced(\"10 seconds\")))"),
  r("foreach-over-yield-loop", "info", "idiomatic", "for-of com yield* no gen — Effect.forEach deixa concurrency explícita.", "Effect.forEach(xs, f, { concurrency: 5 }).", "for (const id of ids) { yield* load(id) }", "yield* Effect.forEach(ids, load, { concurrency: 5 })"),
  r("effect-promise-untyped", "info", "idiomatic", "Effect.promise não tem canal E — use tryPromise com catch.", "Effect.tryPromise({ try, catch }).", "Effect.promise(() => fetch(url))", "Effect.tryPromise({ try: (signal) => fetch(url, { signal }), catch: (e) => new FetchError({ cause: e }) })"),
  r("fail-native-error", "warning", "idiomatic", "Effect.fail(new Error()) — Error nativo não tem _tag.", "Schema.TaggedErrorClass.", "Effect.fail(new Error(\"boom\"))", "return yield* new AppError({ message: \"boom\" })"),
  r("die-string", "warning", "idiomatic", "Effect.die/dieMessage para falha esperada — isso é defect.", "Effect.fail(tagged) / yield* new TaggedError.", "Effect.die(\"nope\")", "return yield* new Invariant({ detail: \"nope\" })"),
  r("option-get-or-throw", "warning", "idiomatic", "Option.getOrThrow / getOrUndefined / getOrNull — perde o Option.", "Option.match / getOrElse / fail com TaggedError.", "Option.getOrThrow(maybe)", "yield* Option.match(maybe, { onNone: () => new NotFound({ id }), onSome: Effect.succeed })"),
  r("json-stringify", "info", "idiomatic", "JSON.stringify lança e não valida.", "Schema.encodeEffect / HttpServerResponse.json.", "JSON.stringify(user)", "yield* Schema.encodeUnknownEffect(User)(user)"),
  r("structured-log", "info", "idiomatic", "JSON.stringify interpolado no log — use annotateLogs.", "Effect.log(\"msg\").pipe(Effect.annotateLogs({ user })).", "Effect.log(`user ${JSON.stringify(user)}`)", "Effect.log(\"user\").pipe(Effect.annotateLogs({ user }))"),
  r("json-http-response", "warning", "idiomatic", "HttpServerResponse.text(JSON.stringify) sem content-type json.", "HttpServerResponse.json(user).", "HttpServerResponse.text(JSON.stringify(user))", "HttpServerResponse.json(user)"),
  r("span-name-generic", "info", "idiomatic", "Effect.fn(\"run\"/\"fn\"/\"x\") — span inútil no trace.", "Effect.fn(\"UserRepo.loadById\").", "Effect.fn(\"run\")(function* () {})", "Effect.fn(\"UserRepo.loadById\")(function* (id: string) { ... })"),
  r("it-effect", "warning", "idiomatic", "it(...) + runPromise — @effect/vitest tem it.effect.", "it.effect(\"nome\", () => program).", "it(\"cria user\", () => Effect.runPromise(program))", "it.effect(\"cria user\", () => program)"),
  r("sql-manual-transaction", "warning", "architecture", "sql`BEGIN/COMMIT/ROLLBACK` na mão.", "sql.withTransaction.", "yield* sql`BEGIN`", "yield* insert.pipe(sql.withTransaction)"),
  r("service-not-class", "info", "idiomatic", "Context.Service em const — no RC o padrão é class.", "class Db extends Context.Service<Db, Shape>()(\"Db\") {}.", "const Db = Context.Service<Shape>()(\"Db\")", "class Db extends Context.Service<Db, Shape>()(\"Db\") {}"),
  r("deterministic-service-key", "info", "idiomatic", "identifier do Service/Tag ≠ nome da classe.", "class Db ... (\"Db\").", "class Db extends Context.Service<Db, Shape>()(\"Database\") {}", "class Db extends Context.Service<Db, Shape>()(\"Db\") {}"),
  r("schema-union-of-literals", "info", "idiomatic", "Union de vários Schema.Literal — Schema.Literals.", "Schema.Literals([\"a\", \"b\"]).", "Schema.Union([Schema.Literal(\"a\"), Schema.Literal(\"b\")])", "Schema.Literals([\"a\", \"b\"])"),
  r("void-effect", "error", "correctness", "`void Effect.*` descarta o Effect — nunca roda.", "yield* / atribua / rode no boundary.", "void Effect.log(\"hi\")", "yield* Effect.log(\"hi\")"),
  r("ignore-errors", "info", "idiomatic", "Effect.ignore engole o canal E.", "catchTag do caso esperado; ignore só se for explícito no nome.", "op.pipe(Effect.ignore)", "op.pipe(Effect.catchTag(\"NotFound\", () => Effect.void))"),

  r("stream-runcollect-infinite", "error", "correctness", "Stream.forever + runCollect nunca termina.", "take/takeUntil/timeout, ou runDrain.", "Stream.forever(poll).pipe(Stream.runCollect)", "Stream.forever(poll).pipe(Stream.take(100), Stream.runCollect)"),
  r("stream-eager-chunk", "info", "performance", "Stream.fromChunk(Chunk.fromIterable) materializa tudo.", "Stream.fromIterable.", "Stream.fromChunk(Chunk.fromIterable(xs))", "Stream.fromIterable(xs)"),
  r("stream-mapeffect-concurrency", "info", "performance", "Stream.mapEffect sem { concurrency } é 1 a 1.", "Passe concurrency explícita.", "Stream.mapEffect(processItem)", "Stream.mapEffect(processItem, { concurrency: 4 })"),
  r("queue-unbounded", "info", "performance", "Queue.unbounded sem backpressure — risco de OOM.", "Queue.bounded(n) / sliding / dropping.", "yield* Queue.unbounded<Job>()", "yield* Queue.bounded<Job>(256)"),
  r("pubsub-unbounded", "info", "performance", "PubSub.unbounded sem backpressure.", "PubSub.bounded(n).", "yield* PubSub.unbounded<Event>()", "yield* PubSub.bounded<Event>(256)"),
  r("new-map-set", "info", "idiomatic", "new Map/Set em código Effect — HashMap/HashSet têm Equal.", "HashMap.fromIterable / HashSet.fromIterable.", "const m = new Map()", "const m = HashMap.empty<string, User>()"),

  r("adopt-async-function", "info", "adoption", "async function no arquivo Effect — fora do runtime.", "Effect.fn(\"nome\")(function* (...) { ... }).", "async function load(id: string) { return await fetch(id) }", "const load = Effect.fn(\"load\")(function* (id: string) { return yield* http.get(id) })"),
  r("adopt-promise-then", "info", "adoption", ".then() é pipe sem E/interrupção.", "Effect.tryPromise + map/flatMap.", "fetchUser(id).then((u) => save(u))", "Effect.tryPromise({ try: () => fetchUser(id), catch: (e) => new FetchError({ cause: e }) }).pipe(Effect.flatMap(save))"),
  r("adopt-await-in-loop", "warning", "adoption", "await em for/while — sequencial e sem interrupção.", "Effect.forEach(..., { concurrency }).", "for (const id of ids) { await load(id) }", "yield* Effect.forEach(ids, load, { concurrency: 5 })"),
  r("adopt-array-foreach", "info", "adoption", "Array.forEach/map com efeito dentro.", "Effect.forEach / Effect.all.", "ids.forEach((id) => { void load(id) })", "yield* Effect.forEach(ids, load, { concurrency: 5 })"),
  r("banned-fp-ts", "warning", "adoption", "fp-ts junto com Effect — duas libs de efeito.", "Option/Either/Array do effect.", "import * as E from \"fp-ts/Either\"", "import { Either } from \"effect\""),
  r("banned-zod", "warning", "adoption", "zod junto com Effect — use Schema.", "Schema.Struct / decodeUnknownEffect.", "import { z } from \"zod\"", "import { Schema } from \"effect\""),
  r("banned-axios", "warning", "adoption", "axios/got/ky/node-fetch — HttpClient do RC.", "import { HttpClient } from \"effect/unstable/http\".", "import axios from \"axios\"", "yield* http.get(url)"),
  r("banned-dotenv", "warning", "adoption", "dotenv lê process.env cru.", "Config / ConfigProvider do effect.", "import \"dotenv/config\"", "yield* Config.redacted(\"TOKEN\")"),
  r("banned-neverthrow", "warning", "adoption", "neverthrow / ts-results — Either do effect.", "Either / Effect.fail.", "import { ok, err } from \"neverthrow\"", "import { Either, Effect } from \"effect\""),
  r("node-child-process", "warning", "idiomatic", "node:child_process — Command do platform/effect.", "Command.make / Command.string.", "import { spawn } from \"node:child_process\"", "yield* Command.string(Command.make(\"ls\"))"),
  r("node-http-import", "warning", "idiomatic", "node:http(s) — HttpClient/HttpServer do RC.", "effect/unstable/http.", "import http from \"node:http\"", "import { HttpClient } from \"effect/unstable/http\""),
  r("node-path-import", "info", "idiomatic", "node:path — Path do platform.", "const path = yield* Path.Path.", "import * as path from \"node:path\"", "const path = yield* Path.Path"),
  r("process-exit", "warning", "idiomatic", "process.exit mata o runtime no meio.", "Effect.fail / die no entry; deixe runPromise rejeitar.", "process.exit(1)", "return yield* new Fatal({ code: 1 })"),

  r("string-kind-guard", "info", "agent-hygiene", "x.kind === \"user\" / x.type === \"x\" stringly-typed.", "Predicate / Match.tag / type guard.", "if (value.kind === \"user\") {}", "Match.value(value).pipe(Match.tag(\"user\", renderUser), Match.exhaustive)"),
  r("array-mutation", "warning", "agent-hygiene", ".push/.splice/.pop muta o array.", "const next = [...xs, item] / Arr.append.", "xs.push(item)", "const xs2 = [...xs, item]"),
  r("object-mutation", "warning", "agent-hygiene", "Atribuição em propriedade / delete / ++.", "spread: { ...obj, k: v }.", "obj.total = n", "const next = { ...obj, total: n }"),
  r("var-keyword", "warning", "agent-hygiene", "`var` — use const.", "const. `var` vaza no function-scope.", "var x = 1", "const x = 1"),
  r("loose-equality", "warning", "type-safety", "`==` / `!=` — use === ou Option.", "=== / Option.fromNullishOr.", "if (x == null) {}", "const value = yield* Option.fromNullishOr(x)"),
  r("require-commonjs", "warning", "agent-hygiene", "require() / module.exports — ESM + import topo.", "import { x } from \"./x.ts\".", "const fs = require(\"node:fs\")", "import * as fs from \"node:fs\""),
  r("typescript-enum", "warning", "agent-hygiene", "enum TS — union + Schema.Literals / Data.taggedEnum.", "type Kind = \"a\" | \"b\".", "enum Kind { A, B }", "const Kind = Schema.Literals([\"a\", \"b\"])"),
  r("as-any", "warning", "type-safety", "`as any` / `as never` silencia o checker.", "unknown + Schema.decodeUnknownEffect.", "value as any", "yield* Schema.decodeUnknownEffect(User)(value)"),
  r("ts-nocheck", "warning", "type-safety", "@ts-nocheck desliga o arquivo inteiro.", "Conserte os tipos.", "// @ts-nocheck", "strict: true e Schema no boundary"),
  r("eslint-disable", "info", "agent-hygiene", "eslint-disable — o agente tapou o alarme.", "Conserte o diagnóstico. Sem disable.", "// eslint-disable-next-line", "escreva o padrão da regra em vez de silenciar"),
  r("debugger-statement", "warning", "agent-hygiene", "`debugger` / eval no fonte.", "Remova. Log com Effect.logDebug.", "debugger", "yield* Effect.logDebug(\"state\").pipe(Effect.annotateLogs({ state }))"),
  r("singleton-get-instance", "warning", "oop", "getInstance() singleton — estado global.", "Context.Service + Layer.effect.", "class Db { static getInstance() { return Db.i ??= new Db() } }", "class Db extends Context.Service<Db, Shape>()(\"Db\") { static layer = Layer.effect(this, makeDb) }"),
  r("event-emitter", "warning", "oop", "EventEmitter / listeners.push — vaza inscrição.", "PubSub / Stream.fromPubSub / SubscriptionRef.", "emitter.on(\"data\", fn)", "yield* PubSub.publish(hub, event)"),
  r("object-literal-includes", "warning", "correctness", "array.includes({ ... }) compara referência — sempre false.", "Equal.equals + Data.struct, ou some com predicado.", "selected.includes({ id: 1 })", "selected.some((u) => Equal.equals(u, Data.struct({ id: 1 })))"),
  r("switch-on-tag", "warning", "idiomatic", "switch (x._tag) não é exhaustive.", "Match.valueTags / Effect.catchTags.", "switch (event._tag) { case \"A\": break }", "Match.valueTags(event, { A: handleA, B: handleB })"),
  r("tsconfig-not-strict", "warning", "type-safety", "tsconfig sem strict: true — o resto das regras fica oco.", "{ \"compilerOptions\": { \"strict\": true } }.", "{ \"strict\": false }", "{ \"compilerOptions\": { \"strict\": true } }"),
  r("for-await-of", "warning", "adoption", "for await-of — Stream do effect.", "Stream.fromAsyncIterable / Stream.runForEach.", "for await (const x of iter) { await f(x) }", "yield* Stream.fromAsyncIterable(iter, (e) => new StreamError({ cause: e })).pipe(Stream.runForEach(f))"),
  r("yield-succeed-literal", "info", "idiomatic", "yield* Effect.succeed(literal) no gen — devolva o valor.", "return 1 / const x = 1.", "const x = yield* Effect.succeed(1)", "const x = 1"),
  r("promise-resolve", "info", "adoption", "Promise.resolve/reject em arquivo Effect.", "Effect.succeed / Effect.fail.", "Promise.resolve(1)", "Effect.succeed(1)"),
]

export const RULE_BY_ID: ReadonlyMap<string, RuleDefinition> = new Map(
  RULES.map((rule) => [rule.id, rule]),
);

export const CATEGORIES: readonly Category[] = [
  "correctness",
  "anti-pattern",
  "idiomatic",
  "v4-migration",
  "agent-hygiene",
  "type-safety",
  "maintainability",
  "performance",
  "adoption",
  "oop",
  "alchemy",
  "security",
  "architecture",
];

export function isKnownCategory(value: string): value is Category {
  return (CATEGORIES as readonly string[]).includes(value);
}

export function findRule(query: string): RuleDefinition | undefined {
  const exact = RULE_BY_ID.get(query) ?? RULE_BY_ID.get(`effect-doctor/${query}`);
  if (exact) return exact;
  const lower = query.toLowerCase();
  return RULES.find(
    (rule) => rule.id.toLowerCase().includes(lower) || rule.id.replace("effect-doctor/", "").includes(lower),
  );
}
